// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXFdNKuKW7g9exBMIyMN4ZSsfrjrIkB0g',
    appId: '1:342082692023:web:c4926624c6556a6f11fe32',
    messagingSenderId: '342082692023',
    projectId: 'firebox-7fc2a',
    databaseURL: 'https://firebox-7fc2a-default-rtdb.firebaseio.com/',
    authDomain: 'firebox-7fc2a.firebaseapp.com',
    storageBucket: 'firebox-7fc2a.appspot.com',
    measurementId: 'G-3FP1SY0WHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4UGOigTXY5pss0vB7sOrcNmpSYvsNQg',
    appId: '1:342082692023:android:81b1cb953957eaee11fe32',
    messagingSenderId: '342082692023',
    databaseURL: 'https://firebox-7fc2a-default-rtdb.firebaseio.com/',
    projectId: 'firebox-7fc2a',
    storageBucket: 'firebox-7fc2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcC007X8Vm3l7OsLgmYI5-tW78e1Xgk3g',
    appId: '1:342082692023:ios:5fbbd82e2cde1eab11fe32',
    messagingSenderId: '342082692023',
    projectId: 'firebox-7fc2a',
    storageBucket: 'firebox-7fc2a.appspot.com',
    iosClientId: '342082692023-o6sii08miqbla3at8dbn4v1eetuns5qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.box',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcC007X8Vm3l7OsLgmYI5-tW78e1Xgk3g',
    appId: '1:342082692023:ios:b76381eeba3fb40b11fe32',
    messagingSenderId: '342082692023',
    projectId: 'firebox-7fc2a',
    storageBucket: 'firebox-7fc2a.appspot.com',
    iosClientId: '342082692023-v221fbv3s5v0dqqbmkrf3k8ckjbkiqd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.box.RunnerTests',
  );
}
