// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfj44SHl6nKOihyceSGZF8baxFdy4XJFY',
    appId: '1:149884457025:web:e5c890cf89ec6625b736c0',
    messagingSenderId: '149884457025',
    projectId: 'footwear-abf3c',
    authDomain: 'footwear-abf3c.firebaseapp.com',
    databaseURL: 'https://footwear-abf3c-default-rtdb.firebaseio.com',
    storageBucket: 'footwear-abf3c.appspot.com',
    measurementId: 'G-SYWMSWTJ0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDagmzhXTDYvkCQOBja-031Wct6plQridQ',
    appId: '1:149884457025:android:92f3accd32f240ceb736c0',
    messagingSenderId: '149884457025',
    projectId: 'footwear-abf3c',
    databaseURL: 'https://footwear-abf3c-default-rtdb.firebaseio.com',
    storageBucket: 'footwear-abf3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtObpkwaHyvtvDEQ83UBIgfCQXEqsQNcU',
    appId: '1:149884457025:ios:a62c5a5b23a2135fb736c0',
    messagingSenderId: '149884457025',
    projectId: 'footwear-abf3c',
    databaseURL: 'https://footwear-abf3c-default-rtdb.firebaseio.com',
    storageBucket: 'footwear-abf3c.appspot.com',
    iosClientId: '149884457025-d33q8gsn2ivf96879r9u00nn86bf5nrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.box',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtObpkwaHyvtvDEQ83UBIgfCQXEqsQNcU',
    appId: '1:149884457025:ios:cb857a3d9886915cb736c0',
    messagingSenderId: '149884457025',
    projectId: 'footwear-abf3c',
    databaseURL: 'https://footwear-abf3c-default-rtdb.firebaseio.com',
    storageBucket: 'footwear-abf3c.appspot.com',
    iosClientId: '149884457025-eu82v97c60bictfsq0eqfpf9k55g5lc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.box.RunnerTests',
  );
}
